export const FORM_REQUEST = 'FORM_REQUEST'
export const FORM_SUCCESS = 'FORM_SUCCESS'
export const FORM_FAILURE = 'FORM_FAILURE'
export const ADD_PAGE = 'ADD_PAGE'
export const MOVE_QUESTION = 'MOVE_QUESTION'